### ISSUE TITLE
Intermittent testShellStage failure

### ISSUE THREAD

**Issue by timwr** [rapid7/metasploit-javapayload#26]
When building this repository the tests sometimes fail like so:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running javapayload.stage.MeterpreterTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.348 sec
Running javapayload.stage.ShellTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE!
testShellStage(javapayload.stage.ShellTest)  Time elapsed: 0.002 sec  <<< FAILURE!
junit.framework.AssertionFailedError: MagicToken missing in shell output: 
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at javapayload.stage.ShellTest.testShellStage(Unknown Source)
Running metasploit.PayloadTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.717 sec
Results :
Failed tests:   testShellStage(javapayload.stage.ShellTest): MagicToken missing in shell output: 
```
As seen here:
https://travis-ci.org/rapid7/metasploit-javapayload/jobs/27319619

This bug is intermittent so it's difficult to ping down what's causing it. The work-around is to rebuild, as it appear to occur about 1 in 10 tries.

@schierlm recommended here: https://github.com/rapid7/metasploit-javapayload/pull/17 that we increase the timeout.

**Comment by timwr** [comment]
Fixed with https://github.com/rapid7/metasploit-javapayload/pull/30 
Thanks guys!
